spring:
    security:
        oauth2:
            client:
              registration:                github:
                  clientId: 2479bfa7d8244889fe13
                  clientSecret: 21915dd8e22b5e7198161b7607cbf27f84078c0d
                  redirectUri: http://104.45.181.0/callback     
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/airbusinventory
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        #show-sql: true
                     
logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

server:
  port: 8085
  
# ...